FROM golang:1.22-alpine

WORKDIR /app

# Download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Bring in rest of the project
COPY . ./

# Build the app for linux
RUN CGO_ENABLED=0 GOOS=linux go build -o /todo-app ./cmd/app/main.go 

EXPOSE 8080

CMD ["/todo-app"]